# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProposalDaisakusen' do

  pod 'SnapKit', '~> 5.0.0'


  target 'ProposalDaisakusenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProposalDaisakusenUITests' do
    # Pods for testing
  end

end
